Agt 25 home page
greenfox-academy/epam-jsa-agate pull request #25
Opened 2017-10-10 10:27 UTC by linjialiang1234

2017-10-11 03:34 UTC, beltekylevi requested changes
let's go through everything in person as well

2017-10-11 03:34 UTC, beltekylevi commented on .application-config.json
>  {
didn't we get rid of this file? 🤔

2017-10-11 03:34 UTC, beltekylevi commented on src/client/app/component/BusinessOverview/index.js
> +    let imagesDetails = [
🍬 put the static data into a separate file and use a little bit more precise placeholder text like lorem ipsum 😄

2017-10-11 03:34 UTC, beltekylevi commented on src/client/app/component/BusinessOverview/index.js
> +    imagesDetails.map(
map returns a list, so you don't have to push into `allBusiness` list manually

2017-10-11 03:34 UTC, beltekylevi commented on src/client/app/component/BusinessOverview/index.js
> +    );
🍬 nice formatting! 🙂

2017-10-11 03:34 UTC, beltekylevi commented on src/client/app/component/HomePage/index.js
> +      <div className = "HomePage">
do you need to add spaces around the `=` sign?

2017-10-11 03:34 UTC, beltekylevi commented on src/client/app/component/HomePage/style.scss
> +.Main{
space after selector

2017-10-11 03:34 UTC, beltekylevi commented on src/client/app/component/HomePage/style.scss
> +.HomePageContainer{
space after selector

2017-10-11 03:34 UTC, beltekylevi commented on src/client/app/component/HomePage/style.scss
> +.HomePageMap{
space after selector

2017-10-11 03:34 UTC, beltekylevi commented on src/client/app/component/HomePageMap/index.js
> +      businesses: [{lat: 22.528640199999998, lng: 113.94},
🍬 put the static data into a separate file

2017-10-11 03:34 UTC, beltekylevi commented on .gitignore
> +*.DS_Store
`.DS_Store`

2017-10-11 03:34 UTC, beltekylevi commented on src/client/app/component/HomePageHeader/style.scss
> +.HomePageHeader{
space after every selector

2017-10-11 03:34 UTC, beltekylevi commented on src/client/app/component/NavigationBar/style.scss
> +#nav-container {
avoid using ids

2017-10-11 03:34 UTC, beltekylevi commented on src/client/app/component/NavigationBar/style.scss
> +#comment-img {
avoid using ids

2017-10-12 04:02 UTC, closed without merging

2017-10-12 04:02 UTC, Jerry-ZWL commented
it was done already by another branch